import { test, expect } from "@playwright/test";

test.describe("Authentication", () => {
  test.describe("Login Page", () => {
    test.beforeEach(async ({ page }) => {
      await page.goto("/login");
    });

    test("login page loads correctly", async ({ page }) => {
      // CardTitle renders as a div - use first() to avoid strict mode
      await expect(page.locator("text=Iniciar sesión").first()).toBeVisible();
      await expect(page.locator('input[id="email"]')).toBeVisible();
      await expect(page.locator('input[id="password"]')).toBeVisible();
      await expect(page.getByRole("button", { name: "Iniciar sesión" })).toBeVisible();
    });

    test("login with invalid credentials shows error", async ({ page }) => {
      await page.fill('input[id="email"]', "invalid@example.com");
      await page.fill('input[id="password"]', "wrongpassword");
      await page.getByRole("button", { name: "Iniciar sesión" }).click();

      // Wait for the error toast to appear
      await expect(page.locator("text=Error al iniciar sesión")).toBeVisible({ timeout: 10000 });
    });

    test("login with valid admin credentials redirects to admin dashboard", async ({ page }) => {
      await page.fill('input[id="email"]', "admin@qaiross.app");
      await page.fill('input[id="password"]', "Admin123!");
      await page.getByRole("button", { name: "Iniciar sesión" }).click();

      // Should redirect to /admin for super_admin
      await expect(page).toHaveURL(/\/admin/, { timeout: 15000 });
    });
  });

  test.describe("Register Page", () => {
    test.beforeEach(async ({ page }) => {
      await page.goto("/register");
    });

    test("register page loads and has form fields", async ({ page }) => {
      // CardTitle renders as a div - use first() to avoid strict mode
      await expect(page.locator("text=Crear cuenta").first()).toBeVisible();

      // Verify form fields by placeholder (IDs are auto-generated by react-hook-form)
      await expect(page.getByPlaceholder("Tu nombre completo")).toBeVisible();
      await expect(page.getByPlaceholder("tu@email.com")).toBeVisible();
      await expect(page.getByPlaceholder("Mínimo 6 caracteres")).toBeVisible();
      await expect(page.getByPlaceholder("Ej: Restaurante El Sabor")).toBeVisible();
      await expect(page.getByRole("button", { name: "Crear cuenta" })).toBeVisible();
    });
  });
});
